"""UI 层类型协议定义。"""

from __future__ import annotations

from typing import Any, Protocol

from desktop_py.core.models import AccountConfig, AppSettings, ScheduleState


class MainWindowProtocol(Protocol):
    """MainWindow 的结构化类型协议，用于 UI action 模块的类型标注。"""

    # ---- 数据属性 ----
    accounts: list[AccountConfig]
    settings: AppSettings
    schedule_state: ScheduleState

    # ---- UI 控件属性 ----
    table: Any
    webhook_edit: Any
    profile_dir_edit: Any
    auto_fetch_push_switch: Any
    login_button: Any
    renew_button: Any
    edit_button: Any
    import_button: Any
    validate_button: Any
    fetch_selected_button: Any
    delete_button: Any
    stop_fetch_button: Any

    # ---- 内部状态属性 ----
    _threads: list[Any]
    _task_runner: Any
    _auto_fetch_timer: Any
    _auto_renew_timer: Any

    # ---- 公共方法 ----
    def append_log(self, message: str) -> None: ...
    def refresh_table(self) -> None: ...
    def selected_account(self) -> AccountConfig | None: ...
    def selected_index(self) -> int: ...
    def selected_indexes(self) -> list[int]: ...
    def statusBar(self) -> Any: ...

    # ---- 内部方法 ----
    def _show_info(self, title: str, text: str) -> None: ...
    def _show_warning(self, title: str, text: str) -> None: ...
    def _update_action_buttons(self) -> None: ...
    def _set_status_text(self, message: str) -> None: ...
    def _run_thread(
        self,
        job_builder: Any,
        on_success: Any,
        *,
        emit_log: bool = ...,
        emit_failure_log: bool = ...,
        update_status: bool = ...,
        on_progress: Any = ...,
    ) -> None: ...
    def _merge_imported_accounts(self, base_account: AccountConfig, names: list[str]) -> None: ...
    def _mark_fetch_result(self, account: AccountConfig, result: Any) -> None: ...
    def _mark_fetch_progress(self, result: Any) -> None: ...
    def _build_fetch_job(self, enabled_accounts: list[AccountConfig]) -> Any: ...
    def _update_current_main_account(self, account_name: str) -> None: ...
    def _send_summary_with_webhook(
        self,
        webhook: str,
        append_batch_log: bool = ...,
        results: list[Any] | None = ...,
    ) -> None: ...
    def _apply_auto_fetch_push_schedule(self) -> None: ...
    def _apply_auto_renew_schedule(self) -> None: ...
    def _run_auto_renew(self) -> None: ...
    def _run_auto_fetch_push(self) -> None: ...
    def _auto_validate_entry_account(self) -> None: ...
    def _milliseconds_until_next_auto_fetch_push(self, now: Any = ...) -> int: ...
    def _login_start_message(self, account: AccountConfig) -> str: ...
    def _mark_login(self, account: AccountConfig) -> None: ...
    def _mark_validation(self, account: AccountConfig, valid: bool) -> None: ...
    def _mark_auto_renew_result(self, account: AccountConfig, valid: bool) -> None: ...
